services:
  - type: web
    name: tarot-divination
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.5
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
